/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ServiceNow brand colors
        'sn-navy': '#081b3a',
        'sn-navy-mid': '#0d2a54',
        'sn-navy-light': '#132f5c',
        'sn-blue': '#1c4f8a',
        'sn-leaf': '#81b532',
        'sn-leaf-dark': '#5e8924',
        'sn-leaf-light': '#a3d152',
        // Legacy design tokens (kept for backwards compat)
        'background': '#040f24',
        'surface': '#081b3a',
        'primary': '#081b3a',
        'primary-container': '#0d2a54',
        'secondary': '#81b532',
        'secondary-fixed': '#a3d152',
        'tertiary': '#1c4f8a',
        'tertiary-fixed': '#d4e8ff',
        'surface-variant': '#0d2a54',
        'surface-container-low': '#081b3a',
        'surface-container-lowest': '#040f24',
        'surface-container-high': '#132f5c',
        'surface-container-highest': '#1c4f8a',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface': '#f1f5f9',
        'on-surface-variant': '#94a3b8',
        'on-primary-container': '#81b532',
        'on-secondary-container': '#5e8924',
        'on-tertiary-container': '#d4e8ff',
        'on-tertiary-fixed-variant': '#1c4f8a',
        'on-primary-fixed': '#040f24',
        'on-secondary-fixed': '#030c1c',
        'on-tertiary-fixed': '#040f24',
        'outline-variant': '#1c4f8a',
        'outline': '#2d6ba8',
        'error': '#f87171',
        'error-container': '#450a0a',
        'on-error': '#ffffff',
        'on-error-container': '#fca5a5',
        'inverse-primary': '#a3d152',
        'inverse-surface': '#f1f5f9',
        'inverse-on-surface': '#040f24',
        'surface-tint': '#1c4f8a',
        'surface-bright': '#132f5c',
        'surface-dim': '#040f24',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Be Vietnam Pro', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif']
      },
      borderRadius: {
        DEFAULT: '2rem',
        lg: '3rem',
        xl: '4rem',
        full: '9999px',
      },
      boxShadow: {
        'editorial': '0 40px 60px -15px rgba(4, 15, 36, 0.18)',
        '2xl': '0 25px 50px -12px rgba(0,0,0,0.35)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
